forktruck:
  # Publish all joint states -----------------------------------
  /joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  /joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: vplate_joint
    pid: {p: 2000.0, i: 1, d: 0.0}
  /joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: fork_joint
    pid: {p: 2000.0, i: 1, d: 0.0}
  /joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: ltooth_joint
    pid: {p: 1000.0, i: 1, d: 0.0}
  /joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: rtooth_joint
    pid: {p: 1000.0, i: 1, d: 0.0}


