footprint: [[-0.23, -0.30], [-0.23, 0.30], [0.23, 0.30], [0.3, 0.0], [0.23, -0.3]]

obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: .3
footprint_padding: 0.01
inflation_radius: 0.55
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}

